[package]
name = "bip44"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
base58 = "0.2.0"
bip39 = "2.0.0"
hmac = "0.12.1"
k256 = "0.13.4"
pbkdf2 = "0.12.2"
rand = "0.8.5"
ripemd = "0.1.3"
secp256k1 = "0.29.1"
sha2 = "0.10.8"
